Edit an entry
alexjraymond/code-journal pull request #7
Opened 2023-01-02 22:38 UTC by alexjraymond

![CleanShot 2023-01-02 at 14 34 51](https://user-images.githubusercontent.com/117477893/210282368-908e846d-c45c-4f8e-9ce7-d8d8f7fa4f1f.gif)

--stuck on the refresh part to update the dom/list, but other than that i think it's there

2023-01-03 17:53 UTC, codingcodymiller requested changes

2023-01-03 17:53 UTC, codingcodymiller commented on js/main.js
> +    data.entries.unshift(editedEntry);
You don't want to add edited entries to the beginning of the list, you want to replace them at the index they were at before editing.

2023-01-03 17:53 UTC, codingcodymiller commented on js/main.js
> +    $entryList.appendChild(editedLiReturn);
Same here, you shouldn't be adding it to the end of the list, you should be replacing the original DOM tree at its original position before editing.

2023-01-03 23:27 UTC, alexjraymond commented
![CleanShot 2023-01-03 at 15 19 38](https://user-images.githubusercontent.com/117477893/210458109-ad5a2f94-40cb-4fba-b0e1-b01abbde60b3.gif)

2023-01-04 16:38 UTC, codingcodymiller requested changes

2023-01-04 16:38 UTC, codingcodymiller commented on js/main.js
> +  }
It doesn't look like you are updating the edited entry's data in `data.entries`. Does your edit persist after you refresh the page?

2023-01-09 22:52 UTC, alexjraymond commented
<img width="931" alt="CleanShot 2023-01-09 at 14 49 46@2x" src="https://user-images.githubusercontent.com/117477893/211424252-2b98739d-be01-45b1-a23d-1a468ae04c78.png">

we did it

2023-01-09 22:56 UTC, codingcodymiller approved these changes

2023-01-09 22:56 UTC, merged